### PR TITLE
LRDOCS-2159 Update image checker to handle missing images, extra images, and faulty image paths

### PR DESCRIPTION
**Pull request by jrao**
https://issues.liferay.com/browse/LRDOCS-2159 Update image checker to handle missing images, extra images, and faulty image paths

### CODE REVIEW

**Comment by jhinkey** [comment]
Hi Jesse,

Can you explain what you mean by extra images?

Thanks,
Jim

On 1/27/2016 4:01 PM, Jesse Rao wrote:
>
> https://issues.liferay.com/browse/LRDOCS-2159 Update image checker to
> handle missing images, extra images, and faulty image paths
>
> ------------------------------------------------------------------------
>
>
>         You can view, comment on, or merge this pull request online at:
>
>   https://github.com/jhinkey/liferay-docs/pull/289
>
>
>         Commit Summary
>
>   * Remove duplicate article
>   * Remove extra '#' char
>   * Merge pull request #1475 from jrao/fix-header-ids
>   * LRDOCS-2159 Update image checker to report missing images, extra
>     images, and faulty image paths. Any of these problems now causes a
>     build failure.
>   * LRDOCS-2159 Add Javadoc to image checker class
>
>
>         File Changes
>
>   * *M* build-site-common.xml
>     <https://github.com/jhinkey/liferay-docs/pull/289/files#diff-0> (16)
>   * *M*
>     code/liferay-doc-utils/src/com/liferay/documentation/util/CheckImagesTaskDevSite.java
>     <https://github.com/jhinkey/liferay-docs/pull/289/files#diff-1> (313)
>   * *M*
>     discover/deployment/articles/02-securing-liferay/08-openid-authentication.markdown
>     <https://github.com/jhinkey/liferay-docs/pull/289/files#diff-2> (2)
>   * *D*
>     discover/deployment/articles/02-securing-liferay/service-access-policies.markdown
>     <https://github.com/jhinkey/liferay-docs/pull/289/files#diff-3> (149)
>   * *M* lib/liferay-doc-utils.jar
>     <https://github.com/jhinkey/liferay-docs/pull/289/files#diff-4> (0)
>
>
>         Patch Links:
>
>   * https://github.com/jhinkey/liferay-docs/pull/289.patch
>   * https://github.com/jhinkey/liferay-docs/pull/289.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhinkey/liferay-docs/pull/289>.
>

-- 
Jim Hinkey
Sr. Knowledge Engineer
Liferay, Inc.
www.liferay.com <http://www.liferay.com>

Visit Us: www.liferay.com <http://www.liferay.com> | Like Us:
facebook.com/liferay <http://facebook.com/liferay> | Follow Us:
twitter.com/liferay <http://twitter.com/liferay>

**Comment by jrao** [comment]
Hey Jim,

Extra images are images that are not referenced by any markdown file. E.g., any images in discover/deployment/images that are not referenced by any markdown files in discover/deployment/articles count as extra images.

**Comment by jhinkey** [comment]
Sounds good. Reviewing now.

**Comment by jrao** [comment]
@jhinkey Hey Jim, I updated the image checker to handle inline images. I tested on discover/portal and on the articles/03-collaboration/02-collaborating/01-publishing-blogs.markdown article in particular. Fixing the path to icon-menu.png resolves the errors, as expected.

**Comment by jhinkey** [comment]
Great, Jesse. I'll review now.

**Comment by jhinkey** [comment]
https://github.com/sez11a/liferay-docs/pull/1477

**Pull request closed without merging**
