### PR TITLE
LRDOCS-2294 added themes intro article to themes and layout templates section

### PR DESCRIPTION
**Pull request by mwilliams2014**
Here is the updated intro, per your notes. Please let me know what you think. Thanks!

### CODE REVIEW

**Comment by mwilliams2014** [comment]
@jhinkey Minor edit needed. Will update :-)

**Comment by mwilliams2014** [comment]
@jhinkey Good to go

**Comment by mwilliams2014** [comment]
@jhinkey updates have been pushed :-)

**Comment by jhinkey** [comment]
Merged into https://github.com/sez11a/liferay-docs/pull/1572
Thanks.

**Pull request closed without merging**
