### PR TITLE
LRDOCS-1852 Liferay 7 JavaScript tutorials

### PR DESCRIPTION
**Pull request by mwilliams2014**

### CODE REVIEW

**Comment by jhinkey** [comment]
Started reviewing. thanks

**Comment by mwilliams2014** [comment]
@jhinkey updated code examples and rebased off of master. If you pulled branch locally, you may need to redo it.

Thanks!

**Comment by jhinkey** [comment]
@mwilliams2014 - Please send this in a PR to Chema so he can update it with the latest code changes. I believe we're using something different from Bower.

**Comment by mwilliams2014** [comment]
Will do @jhinkey thx!

**Pull request closed without merging**
