### PR TITLE
adding-toolbar-menu

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by jhinkey** [comment]
@sez11a - I created https://issues.liferay.com/browse/LRDOCS-1800 for this tutorial.

**Comment by jhinkey** [comment]
Started reviewing. Thanks.

**Comment by jhinkey** [comment]
@sergiogonzalez , @juliocamarero - FYI - We plan to combine content based on this tutorial and the draft Julio wrote in the Product Development retreat doc exercise - https://docs.google.com/a/liferay.com/document/d/1TEM3BiuAd8Xx2VOdYtbRkBJTQOCntG4OCjdajvk0WBM/edit?usp=sharing

**Comment by juliocamarero** [comment]
Keep in mind that we now have a blade template for building portlet toolbar menus. thanks!

**Comment by jhinkey** [comment]
@juliocamarero , Thanks for the head's up. :+1:

**Pull request closed without merging**
