### PR TITLE
LRDOCS-7401 Remove references to "test@liferay.com" email

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
Hi @jhinkey 

After [LPS-84320](https://issues.liferay.com/browse/LPS-84320) and [LRDOCS-7395](https://issues.liferay.com/browse/LRDOCS-7395) changes, we should remove all references to "test@liferay.com" email.

I have done following changes:

- **First commit https://github.com/jhinkey/liferay-docs/commit/0b781a5ad56b0ce35667d6b4a0f24c68c1e0bb8d -** I have updated groovy script to avoid hardcoding "test@liferay.com"
- **Second https://github.com/jhinkey/liferay-docs/commit/2212362cdaf4b1be34bceca736478346cc9a39f9 and third commit https://github.com/jhinkey/liferay-docs/commit/52542fdc4a8b1bf88af5dc64370e793c715ecf98** I have replaced "test@liferay.com" with "test@example.com". For more information about "example.com" domain, see tools.ietf.org/html/rfc6761#section-6.5
- **Fourth commit https://github.com/jhinkey/liferay-docs/commit/24146ce69459fd79c124d1d70b1d62cedb45c394** I have replaced test@liferay.com with a reference to 'admin.email.from.address' portal-ext.properties property

Thank you

/cc @rbohl

### CODE REVIEW

**Comment by jhinkey** [comment]
Reviewing now. Thank you!

**Comment by jhinkey** [comment]
Sent via https://github.com/sez11a/liferay-docs/pull/4722. Thanks, @jorgediaz-lr !

**Comment by jhinkey** [comment]
Hi @jorgediaz-lr  - Are these changes compatible with 7.1 and 7.0 too? If so, I can back port them.

**Comment by jorgediaz-lr** [comment]
Hi @jhinkey

Yes, they can also be applied to 7.1 and 7.0

**Pull request closed without merging**
