### PR TITLE
LRDOCS-5890, Elasticsearch 6.5

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-5890, should publish with FP 5. cc @lipusz

### CODE REVIEW

**Comment by lipusz** [comment]
Hey Rich,

This was forwarded to Jim since you're out, but looks like it has been published. Can you please merge it?

Thanks!

@sez11a

**Comment by lipusz** [comment]
FP5 has been published in December Dec 21, will be announced today.

**Comment by lipusz** [comment]
https://github.com/sez11a/liferay-docs/pull/3804

**Comment by lipusz** [comment]
Can be closed.

**Comment by jhinkey** [comment]
Thanks.

**Pull request closed without merging**
