### PR TITLE
LRDOCS-2684 Wrote Upgrading a Theme Tutorial

### PR DESCRIPTION
**Pull request by mwilliams2014**
@blzaugg FYI

### CODE REVIEW

**Comment by jhinkey** [comment]
Started reviewing. Thanks.

**Comment by mwilliams2014** [comment]
@jhinkey I pushed one more commit fyi.

**Comment by mwilliams2014** [comment]
@jhinkey wordsmithed

**Comment by mwilliams2014** [comment]
@jhinkey updated

**Comment by jhinkey** [comment]
Started reviewing. Thanks.

**Comment by jhinkey** [comment]
https://github.com/mwilliams2014/liferay-docs/pull/81

**Pull request closed without merging**
