### PR TITLE
LRDOCS-1871 liferay theme generator tutorial

### PR DESCRIPTION
**Pull request by mwilliams2014**

### CODE REVIEW

**Comment by jhinkey** [comment]
Started reviewing. Thank you.

**Comment by mwilliams2014** [comment]
@jhinkey Tutorial is ready for review now. Thanks!

**Comment by jhinkey** [comment]
Started reviewing.

**Comment by jhinkey** [comment]
Thanks! Sent https://github.com/sez11a/liferay-docs/pull/1528.

**Pull request closed without merging**
