### PR TITLE
SB, 7.0 - Make example in creating-remote-services consistent: refers to "Blog", but mentions "JournalArticle" entity

### PR DESCRIPTION
**Pull request by lipusz**
Cheers,
Tibor

### CODE REVIEW

**Comment by lipusz** [comment]
Hi Jim,

Do you have any updates on this? @jhinkey

**Comment by lipusz** [comment]
Hi,

Do you have any updates on this? @jhinkey

**Comment by jhinkey** [comment]
Tibor,

I totally overlooked my email notification on your PR and hadn't checked my PR list. So sorry. Thank you for reminding me! :-)

**Comment by jhinkey** [comment]
Sent https://github.com/sez11a/liferay-docs/pull/2306

**Pull request closed without merging**
