### PR TITLE
Form Nav Tutorial

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Jim,

I'm sending you the pull back with my changes and suggestions.
Let me know if you have any question or concern about them.

Thanks!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
@jhinkey I just thought that we didn't include anything about legacy form navigator entries. Should we include that? The idea is that previous to 7.0 developers could add form navigator entries modifing portal.properties with a hook and providing a jsp. That mechanism is still valid for 7.0 but we will deprecate that at some point.

**Comment by jhinkey** [comment]
@sergiogonzalez Good point about mentioning support for legacy approach of adding entries via portal properties in a hook and providing a JSP. I'll add that.

**Comment by jhinkey** [comment]
Started reviewing. I'll test it too. Everything you've mentioned and changed makes sense.
Thanks.

**Comment by jhinkey** [comment]
@sergiogonzalez - Since the old portal properties (e.g., `company.settings.form.*`, `sites.form.update.*`, etc) no longer exist in [portal.properties](http://docs.liferay.com/portal/6.2/propertiesdoc/portal.properties.html), I don't think we should mention customizing the form-navigator using a portal properties hook. Thoughts?

**Comment by sergiogonzalez** [comment]
Hey @jhinkey 
We deprecated that behaviour and that's why we remove the portal.properties, so new installations won't use them, but in case that somebody who upgrades are using them, we make sure that they will still work. 
But yeah, maybe we shouldn't point this out since I guess that this guide is intended for 7.0 developers and we shouldn't specify how to do this before 7.0, right? So maybe we can skip that.

Sergio

**Comment by jhinkey** [comment]
Hi @sergiogonzalez ,

I'll mention that the old form navigator extensions (overriding portal properties and adding nav entry JSPs) are still supported but are deprecated. And I'll add that all new extensions of form navigators should be done as described in this 7.0 tutorial. Thanks for clarifying this.

Jim

**Comment by jhinkey** [comment]
Thanks @sergiogonzalez . I sent the changes in https://github.com/sez11a/liferay-docs/pull/1375.

**Pull request closed without merging**
