### PR TITLE
LRDOCS-2682 Wrote optimizing themes intro

### PR DESCRIPTION
**Pull request by mwilliams2014**

### CODE REVIEW

**Comment by mwilliams2014** [comment]
@jhinkey updated ;-)

**Comment by jhinkey** [comment]
Started reviewing. Thanks.

**Comment by jhinkey** [comment]
Please re-push with the changes I mentioned. thanks.

**Comment by mwilliams2014** [comment]
Superseded by https://github.com/jhinkey/liferay-docs/pull/308

**Pull request closed without merging**
