### PR TITLE
LRDOCS-3721 IDE and Structures and Templates video tutorials

### PR DESCRIPTION
**Pull request by mwilliams2014**
@jhinkey here are the changes. Note that the video files are on LDN and not UAT. I'll upload them to UAT as well for testing.

### CODE REVIEW

**Comment by jhinkey** [comment]
Merged locally for importing to UAT.

**Comment by mwilliams2014** [comment]
@jhinkey fixed a render error in the markdown. Can you please reimport the markdown zip into the KB?

**Comment by jhinkey** [comment]
Sent you https://github.com/mwilliams2014/liferay-docs/pull/116

**Comment by mwilliams2014** [comment]
@jhinkey looks like there was a syntax error with the HTML, can you please reimport. Hopefully this should fix it. Some how, the second div in the markdown file isn't being imported, and I'm guessing it was because of that error. I've merged in your changes into this branch as well. thx!

**Comment by mwilliams2014** [comment]
@jhinkey more SF changes. These latest changes fix the video, so you can watch it by clicking the thumbnail. The issue is that that content in the article is pull into the container and moved over with it now. Please let me know if you can confirm. thx!

**Comment by jhinkey** [comment]
Sent https://github.com/mwilliams2014/liferay-docs/pull/117. Thanks.

**Pull request closed without merging**
