### PR TITLE
LRDOCS-7052 fix broken links in appdev

### PR DESCRIPTION
**Pull request by mwilliams2014**

### CODE REVIEW

**Comment by mwilliams2014** [comment]
missed one, fixing now...

**Comment by mwilliams2014** [comment]
GTG

**Comment by jhinkey** [comment]
Awesome. Reviewing now.

**Comment by jhinkey** [comment]
Holding off on review until after the changes we discussed. Thanks!

**Comment by mwilliams2014** [comment]
Should be GTG @jhinkey , let me know if any other changes are needed. thx!

**Pull request merged**
