### PR TITLE
Update 02-liferay-faces-version-scheme.markdown

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@jhinkey When you get an opportunity, please backport these changes to the 7.1 and 7.0 docs as well. Thanks.

**Comment by jhinkey** [comment]
Will do. Thanks, Neil!

**Comment by ngriffin7a** [comment]
@jhinkey Oh one more change, sorry. For the 5.x branch of Liferay Faces Bridge Ext, please specify "7.0.x / 7.1.x / 7.2.x" instead of "7.0.x/7.1.x" for the Liferay version. Thanks.

**Comment by ngriffin7a** [comment]
@jhinkey I'm closing this PR since I plan on sending an improved one shortly. This one can be ignored.

**Comment by ngriffin7a** [comment]
See https://github.com/jhinkey/liferay-docs/pull/486

**Pull request closed without merging**
