### PR TITLE
LRDOCS-7095 ui concepts redo

### PR DESCRIPTION
**Pull request by mwilliams2014**
@jhinkey Here is the proposed UI Concepts section. I removed my existing article (since it was mostly buzz words and the info is in the theme components and page layout docs), merged yours and added some minor wordsmithing, and migrated the theme components and page layout docs we discussed.  

The only thing perhaps missing now is a high level overview of creating/customizing UI with a basic set of steps, which Rich asked for before. I originally had it here: https://github.com/mwilliams2014/liferay-docs/blob/83dab45320d04485fe851485fc57eeb083885d16/developer/customization/articles/03-architecture/06-ui-concepts/01-understanding-ui-concepts-intro.markdown#a-brief-overview-of-creating-a-theme in my article, but I'm not sure that it fits the new format or if perhaps it should cover brief steps of creating a JS portlet (like a react app) instead.

Let me know what you think. Thanks!

### CODE REVIEW

**Comment by jhinkey** [comment]
I think you should add the theme code to the _Themes_ section of _Understanding UI Concepts_ and explain the code in a paragraph below it.

Also in _Understanding UI Concepts_, I think we should rename the _Product Menu_ section to _Product Navigation Sidebars and Panels_. I like how you referred to it that way in the page layout article.

After you make those changes, I'd be happy to wordsmith.

**Comment by mwilliams2014** [comment]
@jhinkey pushed the changes you suggested

**Comment by jhinkey** [comment]
Started reviewing. Merged locally.

**Comment by mwilliams2014** [comment]
@jhinkey I pushed the updates per our discussion. Let me know what you think. Thanks!

**Comment by jhinkey** [comment]
Superceded by https://github.com/mwilliams2014/liferay-docs/pull/156

**Pull request closed without merging**
